const products = [
  {
    productId: "1100",
    name: "Jameela Attar Oil",
    image: "https://www.bdshop.com/pub/media/catalog/product/cache/3ce43e8bb160f52e76adb2b0bdd9b58d/j/a/jameela-10ml-oil-by-al-haramainohCY.png",
    price: 1200,
    brand: "Al-Haramain",
    rating: 4.5,
    numReviews: 8,
    countInStock: 16,
    volume: "10ml",
    fragranceType: "Perfume Oil",
    fragranceName: "Jameela",
    topNote: "White flowers, Bergamot, Red Plum",
    middleNote: "Strawberry, Jasmine, Sweet",
    baseNote: "Vanilla, Sugary, Musky, Woody",
    description:
      "Sparkling, sensual, seductive. Jameela is a blend of everything you think when the word 'beautiful' comes to mind. With the balmy, lush, fruity, red plum and citric scents harmoniously mingled with succulent, wild strawberry and jasmine, it would be crazy not to wish for the experience to last forever. The sultry, musky and woody notes sweet in the end as in the opening, linger on as gentle memoirs of a fragrance experience you'd love to have every day.",
  },
  {
    productId: "1101",
    name: "Attar Al Kaaba",
    image:
      "https://www.bdshop.com/pub/media/catalog/product/cache/3ce43e8bb160f52e76adb2b0bdd9b58d/a/t/attar-al-kaaba-by-al-haramain.jpg",
    price: 4700,
    brand: "Al-Haramain",
    rating: 4.6,
    numReviews: 12,
    countInStock: 15,
    volume: "25 ML",
    fragranceType: "Perfume Oil",
    fragranceName: "Oriental",
    topNote: "Agarwood (oud), sandalwood, amber and taif rose.",
    middleNote: "amber, Jasmine, Sweet",
    baseNote: "Agarwood (oud), sandalwood, Musky, Woody",
    description:
      "Attar Al Kaaba by Al Haramain Perfumes is an oriental fragrance for Men and Women.Very beautifully blended pure Dehnal Oudh with Amber, Sandal and Taif Rose in a Ka'ba shaped case; the combination of woody, floral, sweet spicy notes makes you feel great.",
  },
  {
    productId: "1102",
    name: "Kawthar Arabian Attar",
    image:
      "https://www.bdshop.com/pub/media/catalog/product/cache/3ce43e8bb160f52e76adb2b0bdd9b58d/k/a/kawthar-arabian-attar-by-swiss-arabianb0J6.jpg",
    price: 1200,
    brand: "Swiss Arabian",
    rating: 4.8,
    numReviews: 15,
    countInStock: 12,
    volume: "15 ML",
    fragranceType: "Perfume Oil",
    fragranceName: "Long-lasting floral",
    topNote: "Agarwood (oud), sandalwood, amber and taif rose.",
    middleNote: "amber, Jasmine, Sweet",
    baseNote: "Agarwood (oud), sandalwood, Musky, Woody",
    description:
      "This Nada Attar by Swiss Arabian 15 ML is nice perfume oil comes in an exquisite fancy designer bottle. It is fully Alcohol-free. It is a skin friendly product. You can be mixed with other fragrances. It has a best for all.",
  },
  {
    productId: "1103",
    name: "Bent Al Ezz Nabah Concen. Perfume",
    image:
      "https://www.bdshop.com/pub/media/catalog/product/cache/3ce43e8bb160f52e76adb2b0bdd9b58d/b/e/bent-al-ezz-nabah-18-ml-concen-perfume-oil-by-rasasi.jpg",
    price: 1800,
    brand: "Rasasi",
    rating: 4.8,
    numReviews: 11,
    countInStock: 19,
    volume: "18 ML",
    fragranceType: "Perfume Oil",
    fragranceName: "Oriental",
    topNote: "Woody, Intense, Spicy, Floral, Fruity",
    middleNote: "amber, Jasmine, Sweet",
    baseNote: "Jasmine, sandalwood, Musky, Woody",
    description:
      "Gentle musk combined with sandalwood draws you into the sweet and fruity an unfinished composition. Join the gently laid tonality bergamot vpouštící together intoxicating jasmine, which peeks and gives way to the sweet seduction broskvovému for the generous contribution of white chocolate. Another fruity notes of ripe and juicy pears along with the plum, in the end, settle in vanilla fragrance intoxication. Now this Bent Al Ezz Nabah 18 ML Concen. perfume oil By Rasasi is Available in Bangladesh",
  },
  {
    productId: "1104",
    name: "Farasha Perfume Oil",
    image:
      "https://www.bdshop.com/pub/media/catalog/product/f/a/al-haramain-farasha-12ml-perfume-oil.jpg",
    price: 2100,
    brand: "Al Haramain",
    rating: 4.6,
    numReviews: 19,
    countInStock: 11,
    volume: "12 ML",
    fragranceType: "Perfume Oil",
    fragranceName: "Farasha",
    topNote: "Woody, Intense, Spicy, Floral, Fruity",
    middleNote: "amber, Jasmine, Sweet",
    baseNote: "Jasmine, sandalwood, Musky, Woody",
    description:
      "The sweetness and warmth of its composition make it ideal for every occasion. Available as a 12 ml perfume oil in a unique boxed bottle. Ideal as a gift. Now this Al Haramain Farasha 12ml is Available in Bangladesh",
  },
];

export default products;
